---
packages:
  core: !include diy-voicepe-esp32-s3.yaml

esphome:
  project:
    name: MorganMLGman.DIY_VoicePE
    version: dev

dashboard_import:
  package_import_url:
    github://MorganMLGman/DIY_VoicePE/diy-voicepe-esp32-s3.yaml@main

esp32_improv:
  authorizer: left_button

improv_serial:

esp32_ble:
  name: diy-voicepe
